# Generated by Django 4.2.15 on 2024-08-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailloginapp', '0007_remove_blog_likes_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
