# Generated by Django 4.2.15 on 2024-08-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailloginapp', '0009_remove_blog_likes_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Liked',
        ),
    ]
