# Generated by Django 4.2.15 on 2024-08-26 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailloginapp', '0012_blog_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_liked',
        ),
    ]
