# Generated by Django 4.2.15 on 2024-08-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailloginapp', '0013_remove_blog_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='liked',
            field=models.BooleanField(null=True),
        ),
    ]
