# Generated by Django 4.2.15 on 2024-08-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailloginapp', '0020_remove_blog_liked_like_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
    ]
