# Generated by Django 4.2.15 on 2024-10-21 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailloginapp', '0027_likebuttonstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likebuttonstatus',
            name='post',
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.ManyToManyField(related_name='liked_blogs', to='emailloginapp.likebuttonstatus'),
        ),
        migrations.AlterField(
            model_name='likebuttonstatus',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
