# Generated by Django 4.2.15 on 2024-10-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailloginapp', '0032_blog_button_status_delete_likebuttonstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='button_status',
        ),
    ]
