# Generated by Django 4.2.15 on 2024-10-25 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailloginapp', '0034_likebuttonstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_blog', models.BooleanField(default=False, null=True)),
                ('edit_blog', models.BooleanField(default=False, null=True)),
                ('delete_blog', models.BooleanField(default=False, null=True)),
                ('edit_user_profile', models.BooleanField(default=False, null=True)),
                ('view_allblogs', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
