# Generated by Django 4.2.15 on 2024-10-26 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailloginapp', '0036_alter_userpermissions_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPermissions',
        ),
    ]
