# Generated by Django 4.2.15 on 2024-10-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailloginapp', '0037_delete_userpermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPermissionsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissionnames', models.CharField(max_length=20)),
            ],
        ),
    ]
