# Generated by Django 4.2.15 on 2024-10-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailloginapp', '0039_userpermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissions',
            name='permissions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emailloginapp.allpermissionslist'),
        ),
    ]
