# Generated by Django 4.2.15 on 2024-10-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailloginapp', '0041_alter_userpermissions_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='button_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
